# Copyright 1999-2010 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild was generated by g-octave

EAPI="3"

inherit octave-forge eutils

DESCRIPTION="This is the Language 1 description"
HOMEPAGE="http://language1.org"
SRC_URI="mirror://sourceforge/octave/${OCT_P}.tar.gz"

LICENSE="|| ( GPL-2 GPL-3 LGPL BSD GFDL )"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

# it's annoying have to see the download of packages from the official
# mirrors fail with a 404 error.
RESTRICT="mirror"

DEPEND=">sci-mathematics/pkg4-1.0.0
	>=sci-mathematics/pkg1-4.3.2
	<sci-mathematics/pkg2-1.2.3
	sci-mathematics/pkg3"
RDEPEND="${DEPEND}
	>=sci-mathematics/octave-3.2.0"

src_prepare() {
	epatch "${FILESDIR}/001_language1-0.0.1.patch"
	epatch "${FILESDIR}/002_language1-0.0.1.patch"
}
